### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'vehicleSummary')

### ISSUE THREAD

**Issue by Jdenmead** [huttotw/homebridge-kia-connect#13]
**Describe Your Problem:**

I have installed this for access to a UK vehicle and Homebridge simply restarts after an error in the log

**Logs:**

[27/04/2024, 22:20:16] Homebridge v1.8.1 (HAP v0.12.0) (Homebridge 9BC3) is running on port 51664.
[27/04/2024, 22:20:17] TypeError: Cannot read properties of undefined (reading 'vehicleSummary')
    at /var/lib/homebridge/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:274:20
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.Do (/var/lib/homebridge/node_modules/homebridge-kia-connect/node_modules/node-singleflight/lib/do.js:30:12)
    at KiaConnect.logIn (/var/lib/homebridge/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:251:5)
    at KiaConnect.vehicleInfo (/var/lib/homebridge/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:191:5)
    at Car.refresh (/var/lib/homebridge/node_modules/homebridge-kia-connect/src/platformAccessory.ts:258:17)
[27/04/2024, 22:20:17] Got SIGTERM, shutting down Homebridge...

**Plugin Config:**

{
    "cars": [
        {
            "name": "EV6",
            "targetTemperature": "64",
            "vin": "REDACTED",
            "refreshInterval": 3600000
        }
    ],
    "email": "REDACTED",
    "password": "REDACTED",
    "_bridge": {
        "username": "REDACTED",
        "port": 38897
    },
    "platform": "KiaConnect"
}

**Screenshots:**

**Environment:**

* **Plugin Version**:
V1.2
* **Homebridge Version**: 
1.8.1
* **Node.js Version**: 
V18.16.0
* **NPM Version**: 
* **Operating System**: 

Raspbian GNU/Linux Buster (10)

**Comment by Binog** [comment]
Have the Same, with an EV3 on node 22.13 and 22.14
