### ISSUE TITLE
Process Ended. Code: 1, Signal: null

### ISSUE THREAD

**Issue by Eureka-127** [huttotw/homebridge-kia-connect#3]
Seam to be stuck in a loop with homebridge. Keep getting the following:

[homebridge-kia-connect] Child bridge process ended
Process Ended. Code: 1, Signal: null

{
    "cars": [
        {
            "name": "Niro",
            "targetTemperature": "70",
            "vin": "xxxx",
            "refreshInterval": 3600000
        }
    ],
    "email": "xxxx",
    "password": "xxxx",
    "_bridge": {
        "username": "xxxx",
        "port": 53154
    },
    "platform": "KiaConnect"
}

[7/16/2023, 12:55:21 PM] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-kia-connect) is running on port 53154.
TypeError: Cannot read properties of undefined (reading 'vehicleSummary')
    at /usr/local/lib/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:274:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.Do (/usr/local/lib/node_modules/homebridge-kia-connect/node_modules/node-singleflight/lib/do.js:30:12)
    at KiaConnect.logIn (/usr/local/lib/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:251:5)
    at KiaConnect.vehicleInfo (/usr/local/lib/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:191:5)
    at Car.refresh (/usr/local/lib/node_modules/homebridge-kia-connect/src/platformAccessory.ts:258:17)
[7/16/2023, 12:55:21 PM] [homebridge-kia-connect] Child bridge process ended
[7/16/2023, 12:55:21 PM] [homebridge-kia-connect] Process Ended. Code: 1, Signal: null
[7/16/2023, 12:55:28 PM] [homebridge-kia-connect] Restarting Process...
[7/16/2023, 12:55:29 PM] [homebridge-kia-connect] Launched child bridge with PID 57766
[7/16/2023, 12:55:29 PM] Registering platform 'homebridge-kia-connect.KiaConnect'
[7/16/2023, 12:55:29 PM] [homebridge-kia-connect] Loaded homebridge-kia-connect v1.2.0 child bridge successfully
[7/16/2023, 12:55:29 PM] Loaded 1 cached accessories from cachedAccessories.xxxxx.
[7/16/2023, 12:55:29 PM] [homebridge-kia-connect] Loading accessory from cache: xxxx
[7/16/2023, 12:55:29 PM] [homebridge-kia-connect] Restoring existing accessory from cache: xxxx
[7/16/2023, 12:55:29 PM] [homebridge-kia-connect] Starting control loop { refreshInterval: 3600000, vin: 'xxxx' }
[7/16/2023, 12:55:29 PM] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-kia-connect) is running on port 53154.
TypeError: Cannot read properties of undefined (reading 'vehicleSummary')
    at /usr/local/lib/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:274:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.Do (/usr/local/lib/node_modules/homebridge-kia-connect/node_modules/node-singleflight/lib/do.js:30:12)
    at KiaConnect.logIn (/usr/local/lib/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:251:5)
    at KiaConnect.vehicleInfo (/usr/local/lib/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:191:5)
    at Car.refresh (/usr/local/lib/node_modules/homebridge-kia-connect/src/platformAccessory.ts:258:17)
[7/16/2023, 12:55:30 PM] [homebridge-kia-connect] Child bridge process ended
[7/16/2023, 12:55:30 PM] [homebridge-kia-connect] Process Ended. Code: 1, Signal: null

**Comment by Edd28** [comment]
Same error here... :( What is the solution?
Thanks!

**Comment by mrrivest** [comment]
Same here. here's my log:

`TypeError: Cannot read properties of undefined (reading 'vehicleSummary')
    at /usr/local/lib/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:273:20
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.Do (/usr/local/lib/node_modules/homebridge-kia-connect/node_modules/node-singleflight/lib/do.js:30:12)
    at KiaConnect.logIn (/usr/local/lib/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:250:5)
    at KiaConnect.vehicleInfo (/usr/local/lib/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:191:5)
    at Car.refresh (/usr/local/lib/node_modules/homebridge-kia-connect/src/platformAccessory.ts:88:17)`

I read it may be because we are in Canada?

**Comment by gitMarcus** [comment]
hi!
same here.
I live in france.

**Comment by huttotw** [comment]
@Edd28 @gitMarcus unfortunately I have only been able to test this plugin in the US. I'll add this as a TODO in the README to see if anyone from other locales is willing to pitch in and debug this.
