### ISSUE TITLE
Homebridge just kept shutting itself down and trying to restart

### ISSUE THREAD

**Issue by tfmteixeira** [huttotw/homebridge-kia-connect#7]
**Describe The Bug:**

Hi! As soon as I installed this plugin and restarted, Homebridge wouldn't load - it just kept shutting itself down and trying to restart.

**To Reproduce:**
Enable Kia plugin and restart Homebridge.

**Logs:**

```
TypeError: Cannot read properties of undefined (reading 'forEach')
    at /var/lib/homebridge/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:274:35
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.Do (/var/lib/homebridge/node_modules/homebridge-kia-connect/node_modules/node-singleflight/lib/do.js:30:12)
    at KiaConnect.logIn (/var/lib/homebridge/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:251:5)
    at KiaConnect.vehicleInfo (/var/lib/homebridge/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:191:5)
    at Car.refresh (/var/lib/homebridge/node_modules/homebridge-kia-connect/src/platformAccessory.ts:258:17)
```

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge 7A36",
        "username": "xxxxxxxxxxxxx",
        "port": 51021,
        "pin": "xxxxxxxxxxxxxx",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "cars": [
                {
                    "name": "Niro EV",
                    "targetTemperature": "68",
                    "vin": "xxxxxxxxxxxxxxx",
                    "refreshInterval": 3600000
                }
            ],
            "email": "xxxxxxxxxxxxxxxxxxx",
            "password": "xxxxxxxxxxxxxxx",
            "platform": "KiaConnect"
        },
    ]
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.0
* **Homebridge Version**: 1.7.0
* **Node.js Version**: 18.19.0
* **NPM Version**: 
* **Operating System**: Debian GNU/Linux Bullseye (11)

**Comment by brian-k** [comment]
I was just having this issue. When I created my Kia account, I used my phone number instead of an email address. For this plug-in, I used the email address, but it could not log in using it. I used my phone number as the login (aka email), and it started working.
