### ISSUE TITLE
client.js     return res.data.payload.remoteStatus === 0 causing a TypeError

### ISSUE THREAD

**Issue by asabatino88** [huttotw/homebridge-kia-connect#9]
**Describe The Bug:**
Homebridge is giving a SIGTERM error as follows when executing a command.

[31m    at KiaConnect.getTransactionStatus (/usr/local/lib/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:55:29)[39m
[31m    at processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
[37m[3/3/2024, 6:14:25 PM] [39mGot SIGTERM, shutting down Homebridge...
[37m[3/3/2024, 6:14:27 PM] [39m[31mTypeError: Cannot read properties of null (reading 'remoteStatus')[39m
[31m    at KiaConnect.getTransactionStatus (/usr/local/lib/node_modules/homebridge-kia-connect/src/kiaconnect/client.ts:55:29)[39m
[31m    at processTicksAndRejections (node:internal/process/task_queues:95:5)[39m

I was able to stop this from happening by commenting out the following code from the client.js. Not sure exactly what this code is trying to do, but appears it's pulling in a null value for some reason (KIA Access was down the past few days, perhaps they changed something on their end).

    // If the transaction is no longer being remotely executed...
    return res.data.payload.remoteStatus === 0;

Again, commenting out     return res.data.payload.remoteStatus === 0; seems to fix the problem. Not sure what other problems it will introduce, but time will tell.

**Comment by johnsills1** [comment]
There was an outage on Kia Connect’s side. I bet if you retry your connection, it’s probably back up now.

**Comment by huttotw** [comment]
@asabatino88 this does seem like an intermitent issue like @johnsills1 mentioned. Have you experienced this recently? If not, will close to clean up some of these issues.

**Comment by asabatino88** [comment]
I completely commented out the line of code that was erroring out in my prior post. I've not noticed any issues with doing so. What is it actually doing?

I will note, my investigation around all of this was due to Kia's servers experiencing an outage a few weekends ago. This outage was making your plugin error out, and then Homebridge got a SIGTERM command and was loop rebooting Homebridge. So all of my Homebridge devices were going offline and back online in a perpetual cycle.

If there is a way to introduce some logic into the plugin where the API call doesn't kill home bridge, that would be a major win in your next release.
